### PR TITLE
change to the master system code

### PR DESCRIPTION
**Pull request by Blaasvis**
Hi, 

We have talked on assembler forums a bit back. 
I did the master system mod yesterday and ran into a problem. The reset button was pulled to ground constantly. So it made the console reboot every second or so. I just add a release reset to the startup and it made the issues go away.

### CODE REVIEW

**Comment by borti4938** [comment]
Thank you for reporting :)
Actually, I don't own a Maser System. I have written the code for a friend of mine. It seems like that I have introduced an error while have done a code refactoring.
I'm really sorry for that!!!
If you have time and if you have put the PIC on a socket, could you test the following:
https://dl.dropboxusercontent.com/u/18680455/MasterSystem_FM_BIOS.zip
I have removed the actual mistake (wrong initialization of TRISA).

**Comment by Blaasvis** [comment]
I did message you on assembler games as well. If you like i have a kinda beat up master system 2. Which i could ship out to you.

**Comment by borti4938** [comment]
Sorry, I don't want to own a Master System. No space, no time, no interests :/

**Comment by Blaasvis** [comment]
Pff it is awesome. But no problem i have one more master system 1 which need to be redone. So i will test it then. I made a socketed project board last night to figure out what was going wrong so i will use that on that system.

**Pull request merged**
